-- 앱을 중지하고 백업한 뒤 적용. 기존 납부 이력은 소급 차감하지 않는다.
BEGIN;
ALTER TABLE initial_installment ADD COLUMN IF NOT EXISTS first_payment_date date;
ALTER TABLE initial_installment DROP CONSTRAINT IF EXISTS initial_installment_remaining_months_check;
ALTER TABLE initial_installment ADD CONSTRAINT initial_installment_remaining_months_check CHECK (remaining_months BETWEEN 0 AND 120);

-- 기존 등록분은 다음 도래 결제일부터 시작한다. 이미 처리한 결제월 이후로 배치한다.
WITH dates AS (
 SELECT i.id,c.payment_day,
   greatest(
     date_trunc('month', timezone('Asia/Seoul',now()))::date +
       CASE WHEN least(c.payment_day, extract(day FROM (date_trunc('month',timezone('Asia/Seoul',now())) + interval '1 month - 1 day'))::int)
         < extract(day FROM timezone('Asia/Seoul',now()))::int THEN interval '1 month' ELSE interval '0 month' END,
     coalesce((SELECT date_trunc('month',max(o.due_date)) + interval '1 month'
       FROM planned_occurrence o WHERE o.source_key='CARD:'||c.id AND o.state IN ('COMPLETED','CANCELLED')),
       date_trunc('month',timezone('Asia/Seoul',now())))
   )::date AS month_start
 FROM initial_installment i JOIN payment_card c ON c.id=i.card_id
 WHERE i.first_payment_date IS NULL
)
UPDATE initial_installment i SET first_payment_date = d.month_start +
 (least(d.payment_day,extract(day FROM (d.month_start + interval '1 month - 1 day'))::int)-1)
FROM dates d WHERE i.id=d.id;
ALTER TABLE initial_installment ALTER COLUMN first_payment_date SET NOT NULL;
UPDATE initial_installment SET active=false WHERE remaining_amount=0 OR remaining_months=0;

CREATE TABLE IF NOT EXISTS installment_schedule (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 installment_id bigint NOT NULL REFERENCES initial_installment(id) ON DELETE RESTRICT,
 due_date date NOT NULL,
 amount numeric(24,2) NOT NULL CHECK(amount>0),
 state varchar(12) NOT NULL CHECK(state IN ('PENDING','PAID','CANCELLED')),
 occurrence_id bigint REFERENCES planned_occurrence(id) ON DELETE RESTRICT,
 paid_date date,
 CHECK ((state='PAID' AND occurrence_id IS NOT NULL AND paid_date IS NOT NULL) OR
        (state<>'PAID' AND occurrence_id IS NULL AND paid_date IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_installment_schedule_active_date
 ON installment_schedule(installment_id,due_date) WHERE state<>'CANCELLED';

INSERT INTO installment_schedule(installment_id,due_date,amount,state)
SELECT i.id,
 (date_trunc('month',i.first_payment_date)+n*interval '1 month')::date +
   (least(c.payment_day,extract(day FROM (date_trunc('month',i.first_payment_date)+(n+1)*interval '1 month'-interval '1 day'))::int)-1),
 CASE WHEN n=i.remaining_months-1 THEN i.remaining_amount-trunc(i.remaining_amount/i.remaining_months,2)*n
      ELSE trunc(i.remaining_amount/i.remaining_months,2) END,
 'PENDING'
FROM initial_installment i JOIN payment_card c ON c.id=i.card_id
CROSS JOIN LATERAL generate_series(0,i.remaining_months-1) n
WHERE i.active AND NOT EXISTS (SELECT 1 FROM installment_schedule s WHERE s.installment_id=i.id);
COMMIT;
