package com.family.asset.service;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.family.asset.dto.*;
import com.family.asset.enums.*;
import com.family.asset.mapper.*;
import com.family.asset.exception.BusinessException;
import java.math.*;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
class CardBillingServiceTest {
 final CardMapper cards=mock(CardMapper.class);final EntryMapper entries=mock(EntryMapper.class);
 final InstallmentMapper installments=mock(InstallmentMapper.class);final InstallmentScheduleMapper schedules=mock(InstallmentScheduleMapper.class);
 final OccurrenceMapper occurrences=mock(OccurrenceMapper.class);final OperationMapper ops=mock(OperationMapper.class);
 final CardBillingService service=new CardBillingService(cards,entries,installments,schedules,occurrences,ops);
 Card card(long id){var c=new Card();c.setId(id);c.setCardName("test");c.setCardType(CardType.CREDIT);c.setOwnerCode(OwnerCode.HUSBAND);c.setStatus(AssetStatus.ACTIVE);c.setAccountId(1L);c.setPaymentDay(14);c.setBillingClosingDay(31);c.setBillingMonthOffset(1);return c;}
 Entry entry(long id,String date,String amount,int months){var e=new Entry();e.setId(id);e.setCardId(1L);e.setTransactionDate(LocalDate.parse(date));e.setAmount(new BigDecimal(amount));e.setInstallmentMonths(months);e.setPaymentMethod(PaymentMethod.CREDIT);e.setTransactionType(TransactionType.EXPENSE);e.setVoided(false);return e;}
 @BeforeEach void setup(){when(cards.findAll()).thenReturn(List.of(card(1)));when(entries.findAll()).thenReturn(List.of());when(installments.findAll()).thenReturn(List.of());when(schedules.findAll()).thenReturn(List.of());when(occurrences.findAll()).thenReturn(List.of());}
 @Test void monthEndLeapYearAndClosingBoundary(){var c=card(1);var p=CardBillingService.period(c,YearMonth.of(2024,3));assertEquals(LocalDate.of(2024,2,1),p.from());assertEquals(LocalDate.of(2024,2,29),p.to());assertEquals(YearMonth.of(2024,3),CardBillingService.firstMonth(c,LocalDate.of(2024,2,29)));c.setBillingClosingDay(15);assertEquals(YearMonth.of(2026,10),CardBillingService.firstMonth(c,LocalDate.of(2026,9,15)));assertEquals(YearMonth.of(2026,11),CardBillingService.firstMonth(c,LocalDate.of(2026,9,16)));assertEquals(LocalDate.of(2026,8,16),CardBillingService.period(c,YearMonth.of(2026,10)).from());}
 @Test void periodsAreContiguousAndEveryDayMapsBack(){var c=card(1);for(int day=1;day<=31;day++)for(int offset=0;offset<=2;offset++){c.setBillingClosingDay(day);c.setBillingMonthOffset(offset);for(var date=LocalDate.of(2023,12,1);date.isBefore(LocalDate.of(2025,4,1));date=date.plusDays(1)){var month=CardBillingService.firstMonth(c,date);var p=CardBillingService.period(c,month);assertFalse(date.isBefore(p.from())||date.isAfter(p.to()));assertEquals(p.from(),CardBillingService.period(c,month.minusMonths(1)).to().plusDays(1));}}}
 @Test void sumsInstallmentsWithoutLosingRemainderAndExcludesVoidedDebit(){var a=entry(1,"2026-09-30","100.00",3);var cancelled=entry(2,"2026-09-10","500",1);cancelled.setVoided(true);var debit=entry(3,"2026-09-10","700",1);debit.setPaymentMethod(PaymentMethod.DEBIT);when(entries.findAll()).thenReturn(List.of(a,cancelled,debit));BigDecimal total=BigDecimal.ZERO;for(int m=10;m<=12;m++){var result=service.month(YearMonth.of(2026,m),"JOINT");assertEquals(1,result.cards().getFirst().lines().size());total=total.add(result.cards().getFirst().expected());}assertEquals(new BigDecimal("100.00"),total);assertEquals(new BigDecimal("33.34"),service.month(YearMonth.of(2026,12),"JOINT").cards().getFirst().expected());verifyNoInteractions(ops);}
 @Test void missingSettingsDoesNotGuessBillingPeriod(){var c=card(1);c.setBillingClosingDay(null);c.setBillingMonthOffset(null);when(cards.findAll()).thenReturn(List.of(c));when(entries.findAll()).thenReturn(List.of(entry(1,"2026-09-01","100",1)));var result=service.month(YearMonth.of(2026,10),"JOINT");assertFalse(result.cards().getFirst().configured());assertNull(result.accounts().getFirst().difference());assertFalse(result.accounts().getFirst().completeEstimate());}
 @Test void legacySourceReplacesDerivedInstallmentAndRetainsPaidSchedule(){var e=entry(1,"2026-09-01","100",3);when(entries.findAll()).thenReturn(List.of(e));var i=new Installment();i.setId(8L);i.setCardId(1L);i.setSourceEntryId(1L);when(installments.findAll()).thenReturn(List.of(i));var s=new InstallmentSchedule();s.setId(10L);s.setInstallmentId(8L);s.setDueDate(LocalDate.of(2026,10,14));s.setAmount(new BigDecimal("33.33"));s.setState("PAID");when(schedules.findAll()).thenReturn(List.of(s));var result=service.month(YearMonth.of(2026,10),"JOINT");assertEquals(1,result.cards().getFirst().lines().size());assertTrue(result.cards().getFirst().lines().getFirst().linked());assertEquals("COMPLETED",result.cards().getFirst().lines().getFirst().status());}
 @Test void accountPaymentIsCountedOnceAndOwnerPartialComparisonIsDisabled(){var c2=card(2);c2.setOwnerCode(OwnerCode.WIFE);when(cards.findAll()).thenReturn(List.of(card(1),c2));var e=entry(1,"2026-09-01","100",1);var e2=entry(2,"2026-09-01","200",1);e2.setCardId(2L);when(entries.findAll()).thenReturn(List.of(e,e2));List<Occurrence> oo=new ArrayList<>();for(long id=1;id<=2;id++){var o=new Occurrence();o.setId(id);o.setCardId(id);o.setSourceKey("CARD:"+id);o.setAccountId(1L);o.setDueDate(LocalDate.of(2026,10,14));o.setState("COMPLETED");o.setPaymentGroupId(10L);oo.add(o);}var group=new Occurrence();group.setId(10L);group.setActualAmount(new BigDecimal("290"));oo.add(group);when(occurrences.findAll()).thenReturn(oo);var result=service.month(YearMonth.of(2026,10),"JOINT");assertEquals(new BigDecimal("290"),result.accounts().getFirst().actualAmount());assertEquals(0,new BigDecimal("-10").compareTo(result.accounts().getFirst().difference()));assertNull(service.month(YearMonth.of(2026,10),"HUSBAND").accounts().getFirst().difference());}
 @Test void validatesSameMonthClosingAndSourceCard(){var c=card(1);c.setBillingMonthOffset(0);assertThrows(BusinessException.class,()->CardBillingService.validate(c));var i=new Installment();i.setId(8L);i.setCardId(2L);when(installments.findById(8L)).thenReturn(i);when(entries.findById(1L)).thenReturn(entry(1,"2026-09-01","100",3));assertThrows(BusinessException.class,()->service.link(8L,1L));verify(installments,never()).linkSource(any(),any());}
}
