package com.family.asset.service;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.family.asset.dto.*;
import com.family.asset.enums.*;
import com.family.asset.mapper.*;
import com.family.asset.exception.BusinessException;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
class ReviewServiceTest {
 final EntryMapper entries=mock(EntryMapper.class);final CategoryMapper categories=mock(CategoryMapper.class);final CardMapper cards=mock(CardMapper.class);final AccountMapper accounts=mock(AccountMapper.class);final InstallmentMapper installments=mock(InstallmentMapper.class);final InstallmentScheduleMapper schedules=mock(InstallmentScheduleMapper.class);final OperationMapper ops=mock(OperationMapper.class);
 final ReviewService review=new ReviewService(entries,categories,cards,accounts,installments,schedules,ops);
 final OffsetDateTime now=OffsetDateTime.parse("2026-09-30T10:00:00+09:00");
 Entry entry(long id){var e=new Entry();e.setId(id);e.setTransactionDate(LocalDate.of(2026,9,15));e.setTransactionType(TransactionType.EXPENSE);e.setPaymentMethod(PaymentMethod.CREDIT);e.setCardId(1L);e.setAmount(new BigDecimal("300"));e.setAttribution(Attribution.HUSBAND);e.setOrigin("MANUAL");e.setVoided(false);e.setInstallmentMonths(3);return e;}
 Card card(){var c=new Card();c.setId(1L);c.setCardName("test");c.setStatus(AssetStatus.ACTIVE);c.setOwnerCode(OwnerCode.HUSBAND);c.setCardType(CardType.CREDIT);c.setPaymentDay(14);return c;}
 Category category(long id,String name){var c=new Category();c.setId(id);c.setName(name);c.setActive(true);c.setTransactionType(TransactionType.EXPENSE);return c;}
 @BeforeEach void init(){when(entries.findAll()).thenReturn(List.of());when(categories.findAll()).thenReturn(List.of());when(cards.findAll()).thenReturn(List.of());when(accounts.findAll()).thenReturn(List.of());when(installments.findAll()).thenReturn(List.of());when(schedules.findAll()).thenReturn(List.of());}
 @Test void categoryIncludesUnclassifiedAndMissingButNotVoidedOrTransfersAndRespectsOwner(){var e=entry(1);e.setCategoryId(5L);var v=entry(2);v.setVoided(true);var t=entry(3);t.setTransactionType(TransactionType.TRANSFER);when(entries.findAll()).thenReturn(List.of(e,v,t));when(categories.findAll()).thenReturn(List.of(category(5,"미분류")));assertEquals(1,review.list("HUSBAND",now).total());assertEquals(0,review.list("WIFE",now).total());assertEquals("classify",review.list("JOINT",now).items().getFirst().action());verifyNoInteractions(ops);}
 @Test void onlyActiveCreditCardsNeedPeriods(){var c=card();when(cards.findAll()).thenReturn(List.of(c));assertEquals(1,review.list("JOINT",now).counts().get("CARD_PERIOD"));c.setBillingClosingDay(31);c.setBillingMonthOffset(1);assertEquals(0,review.list("JOINT",now).total());c.setBillingClosingDay(null);c.setCardType(CardType.DEBIT);assertEquals(0,review.list("JOINT",now).total());}
 @Test void onlyOldActiveLinkedSecuritiesAreFlagged(){var a=new Account();a.setId(1L);a.setAccountName("test");a.setAssetType(AssetType.SECURITIES);a.setStatus(AssetStatus.ACTIVE);a.setOwnerCode(OwnerCode.WIFE);a.setKisLinked(true);a.setLastSyncedAt(now.minusDays(8));when(accounts.findAll()).thenReturn(List.of(a));assertEquals(1,review.list("WIFE",now).total());assertEquals(0,review.list("HUSBAND",now).total());a.setLastSyncedAt(now.minusDays(2));assertEquals(0,review.list("JOINT",now).total());a.setLastSyncedAt(null);a.setKisLinked(false);assertEquals(0,review.list("JOINT",now).total());}
 @Test void legacyOverlapRequiresMatchingCardAndBillingMonth(){var c=card();c.setBillingClosingDay(31);c.setBillingMonthOffset(1);when(cards.findAll()).thenReturn(List.of(c));var i=new Installment();i.setId(8L);i.setCardId(1L);i.setActive(true);i.setRemainingMonths(3);when(installments.findAll()).thenReturn(List.of(i));var s=new InstallmentSchedule();s.setInstallmentId(8L);s.setDueDate(LocalDate.of(2026,10,14));s.setState("PENDING");when(schedules.findAll()).thenReturn(List.of(s));var e=entry(1);when(entries.findAll()).thenReturn(List.of(e));assertEquals(1,review.list("JOINT",now).counts().get("INSTALLMENT"));i.setSourceEntryId(1L);assertEquals(0,review.list("JOINT",now).counts().get("INSTALLMENT"));e.setVoided(true);assertEquals(1,review.list("JOINT",now).counts().get("INSTALLMENT"));i.setActive(false);assertEquals(0,review.list("JOINT",now).counts().get("INSTALLMENT"));}
 @Test void classifyChangesOnlyCategoryAndAuditsWithoutBalanceEffects(){var e=entry(1);e.setCategoryId(5L);when(entries.findById(1L)).thenReturn(e);when(categories.findById(6L)).thenReturn(category(6,"식비"));when(entries.updateCategory(1L,6L)).thenReturn(1);review.classify(1L,6L,5L);verify(ops).lock();verify(ops).categoryChange(1L,5L,6L);verify(ops,never()).changeBalance(any(),any());verify(entries,never()).update(any());verify(entries,never()).insert(any());verify(entries).updateCategory(1L,6L);}
 @Test void classifyRejectsWrongTypeStaleAndAutomaticTransactions(){var e=entry(1);e.setCategoryId(5L);when(entries.findById(1L)).thenReturn(e);var c=category(6,"식비");when(categories.findById(6L)).thenReturn(c);assertThrows(BusinessException.class,()->review.classify(1L,6L,4L));c.setTransactionType(TransactionType.INCOME);assertThrows(BusinessException.class,()->review.classify(1L,6L,5L));e.setOrigin("KIS");assertThrows(BusinessException.class,()->review.classify(1L,6L,5L));verify(entries,never()).updateCategory(any(),any());verify(ops,never()).categoryChange(any(),any(),any());}
}
