CREATE TABLE IF NOT EXISTS allowance_record (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 owner_code varchar(10) NOT NULL CHECK(owner_code IN ('HUSBAND','WIFE')),
 record_date date NOT NULL,
 amount numeric(24,2) NOT NULL CHECK(amount <> 0),
 memo varchar(300) NOT NULL DEFAULT '',
 source_entry_id bigint UNIQUE REFERENCES ledger_entry(id),
 request_id uuid UNIQUE,
 active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK((source_entry_id IS NULL AND request_id IS NOT NULL) OR (source_entry_id IS NOT NULL AND request_id IS NULL))
);
CREATE INDEX IF NOT EXISTS allowance_owner_date_idx ON allowance_record(owner_code,record_date);
