CREATE TABLE IF NOT EXISTS entry_category_change (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 entry_id bigint NOT NULL REFERENCES ledger_entry(id),
 old_category_id bigint REFERENCES category(id),
 new_category_id bigint NOT NULL REFERENCES category(id),
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS entry_category_change_entry_idx ON entry_category_change(entry_id,created_at);
