BEGIN;
CREATE TABLE asset_account (
 display_order integer NOT NULL DEFAULT 2147483647 CHECK(display_order>=0),
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 asset_type varchar(20) NOT NULL CHECK(asset_type IN ('CASH','SAVINGS','SECURITIES')),
 owner_code varchar(10) NOT NULL CHECK(owner_code IN ('HUSBAND','WIFE')),
 institution_code varchar(30) NOT NULL,
 account_name varchar(100) NOT NULL,
 account_number varchar(60) NOT NULL,
 current_balance_krw numeric(24,2) NOT NULL DEFAULT 0,
 currency_code varchar(3) NOT NULL DEFAULT 'KRW' CHECK(currency_code='KRW'),
 status varchar(10) NOT NULL CHECK(status IN ('ACTIVE','CLOSED')),
 kis_linked boolean NOT NULL DEFAULT false,
 start_date date,
 maturity_date date,
 interest_rate numeric(12,8) CHECK(interest_rate>=0),
 monthly_amount numeric(24,2) CHECK(monthly_amount>0),
 payment_day integer CHECK(payment_day BETWEEN 1 AND 31),
 withdrawal_account_id bigint REFERENCES asset_account(id) ON DELETE RESTRICT,
 deposit_krw numeric(24,2) NOT NULL DEFAULT 0,
 deposit_usd numeric(24,2) NOT NULL DEFAULT 0,
 exchange_rate numeric(18,8) NOT NULL DEFAULT 1 CHECK(exchange_rate>0),
 last_synced_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(institution_code, account_number),
 CHECK(asset_type='SECURITIES' OR NOT kis_linked),
 CHECK(withdrawal_account_id IS NULL OR withdrawal_account_id<>id),
 CHECK(maturity_date IS NULL OR start_date IS NULL OR maturity_date>=start_date)
);
CREATE TABLE payment_card (
 display_order integer NOT NULL DEFAULT 2147483647 CHECK(display_order>=0),
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 card_name varchar(100) NOT NULL,
 owner_code varchar(10) NOT NULL CHECK(owner_code IN ('HUSBAND','WIFE')),
 card_type varchar(10) NOT NULL CHECK(card_type IN ('DEBIT','CREDIT')),
 account_id bigint NOT NULL REFERENCES asset_account(id) ON DELETE RESTRICT,
 payment_day integer CHECK(payment_day BETWEEN 1 AND 31),
 status varchar(10) NOT NULL CHECK(status IN ('ACTIVE','CLOSED')),
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK((card_type='CREDIT' AND payment_day IS NOT NULL) OR (card_type='DEBIT' AND payment_day IS NULL))
);
CREATE TABLE loan (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 loan_name varchar(100) NOT NULL,
 owner_code varchar(10) NOT NULL CHECK(owner_code IN ('HUSBAND','WIFE')),
 initial_amount numeric(24,2) NOT NULL CHECK(initial_amount>0),
 current_balance numeric(24,2) NOT NULL CHECK(current_balance>=0),
 interest_rate numeric(12,8) NOT NULL CHECK(interest_rate>=0),
 maturity_date date NOT NULL,
 repayment_type varchar(30) NOT NULL CHECK(repayment_type IN ('EQUAL_PRINCIPAL','ANNUITY','BULLET')),
 payment_day integer NOT NULL CHECK(payment_day BETWEEN 1 AND 31),
 account_id bigint NOT NULL REFERENCES asset_account(id) ON DELETE RESTRICT,
 status varchar(10) NOT NULL CHECK(status IN ('ACTIVE','CLOSED')),
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE category (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(80) NOT NULL,
 transaction_type varchar(10) NOT NULL CHECK(transaction_type IN ('INCOME','EXPENSE')),
 parent_id bigint REFERENCES category(id) ON DELETE RESTRICT,
 active boolean NOT NULL DEFAULT true,
 system_code varchar(40) UNIQUE,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK(parent_id IS NULL OR parent_id<>id)
);
CREATE TABLE ledger_entry (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 transaction_date date NOT NULL,
 transaction_type varchar(10) NOT NULL CHECK(transaction_type IN ('INCOME','EXPENSE','TRANSFER')),
 amount numeric(24,2) NOT NULL CHECK(amount>0),
 attribution varchar(10) NOT NULL CHECK(attribution IN ('JOINT','HUSBAND','WIFE')),
 category_id bigint REFERENCES category(id) ON DELETE RESTRICT,
 payment_method varchar(10) CHECK(payment_method IN ('ACCOUNT','DEBIT','CREDIT')),
 source_account_id bigint REFERENCES asset_account(id) ON DELETE RESTRICT,
 target_account_id bigint REFERENCES asset_account(id) ON DELETE RESTRICT,
 card_id bigint REFERENCES payment_card(id) ON DELETE RESTRICT,
 installment_months integer NOT NULL DEFAULT 1 CHECK(installment_months BETWEEN 1 AND 120),
 memo varchar(1000),
 origin varchar(20) NOT NULL DEFAULT 'MANUAL',
 voided boolean NOT NULL DEFAULT false,
 replaces_id bigint REFERENCES ledger_entry(id) ON DELETE RESTRICT,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE initial_installment (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 card_id bigint NOT NULL REFERENCES payment_card(id) ON DELETE RESTRICT,
 remaining_months integer NOT NULL CHECK(remaining_months BETWEEN 0 AND 120),
 remaining_amount numeric(24,2) NOT NULL CHECK(remaining_amount>=0),
 first_payment_date date NOT NULL,
 memo varchar(1000),
 active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE recurring_plan (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title varchar(100) NOT NULL,
 plan_type varchar(20) NOT NULL CHECK(plan_type IN ('EXPENSE','CARD_PAYMENT','SAVINGS','LOAN')),
 repeat_cycle varchar(10) NOT NULL CHECK(repeat_cycle IN ('ONCE','WEEKLY','MONTHLY','YEARLY')),
 start_date date NOT NULL,
 end_date date,
 amount numeric(24,2) CHECK(amount>0),
 attribution varchar(10) NOT NULL CHECK(attribution IN ('JOINT','HUSBAND','WIFE')),
 category_id bigint REFERENCES category(id) ON DELETE RESTRICT,
 account_id bigint REFERENCES asset_account(id) ON DELETE RESTRICT,
 target_account_id bigint REFERENCES asset_account(id) ON DELETE RESTRICT,
 card_id bigint REFERENCES payment_card(id) ON DELETE RESTRICT,
 loan_id bigint REFERENCES loan(id) ON DELETE RESTRICT,
 active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE planned_occurrence (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_key varchar(100) NOT NULL,
 due_date date NOT NULL,
 title varchar(160) NOT NULL,
 plan_type varchar(20) NOT NULL,
 plan_id bigint REFERENCES recurring_plan(id) ON DELETE RESTRICT,
 account_id bigint REFERENCES asset_account(id) ON DELETE RESTRICT,
 target_account_id bigint REFERENCES asset_account(id) ON DELETE RESTRICT,
 card_id bigint REFERENCES payment_card(id) ON DELETE RESTRICT,
 loan_id bigint REFERENCES loan(id) ON DELETE RESTRICT,
 attribution varchar(10) NOT NULL,
 amount numeric(24,2),
 category_id bigint REFERENCES category(id) ON DELETE RESTRICT,
 state varchar(12) NOT NULL CHECK(state IN ('PENDING','COMPLETED','CANCELLED')),
 actual_date date,
 actual_amount numeric(24,2),
 entry_id bigint REFERENCES ledger_entry(id) ON DELETE RESTRICT,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(source_key,due_date)
);
CREATE TABLE security_holding (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id bigint NOT NULL REFERENCES asset_account(id) ON DELETE RESTRICT,
 symbol varchar(40) NOT NULL,
 name varchar(120) NOT NULL,
 currency_code varchar(3) NOT NULL CHECK(currency_code IN ('KRW','USD')),
 quantity numeric(24,8) NOT NULL,
 average_price numeric(24,8) NOT NULL,
 current_price numeric(24,8) NOT NULL,
 value_native numeric(24,2) NOT NULL,
 value_krw numeric(24,2) NOT NULL,
 exchange_rate numeric(18,8) NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(account_id,symbol,currency_code)
);
CREATE TABLE security_trade (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id bigint NOT NULL REFERENCES asset_account(id) ON DELETE RESTRICT,
 external_id varchar(200) NOT NULL,
 trade_date date NOT NULL,
 trade_type varchar(20) NOT NULL CHECK(trade_type IN ('BUY','SELL','DEPOSIT','WITHDRAWAL','DIVIDEND')),
 symbol varchar(40),
 currency_code varchar(3) NOT NULL CHECK(currency_code IN ('KRW','USD')),
 quantity numeric(24,8) NOT NULL DEFAULT 0,
 amount numeric(24,2) NOT NULL,
 exchange_rate numeric(18,8) NOT NULL,
 entry_id bigint REFERENCES ledger_entry(id) ON DELETE RESTRICT,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(account_id,external_id)
);
CREATE TABLE entry_effect (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
entry_id bigint NOT NULL REFERENCES ledger_entry(id),
account_id bigint NOT NULL REFERENCES asset_account(id),
delta numeric(24,2) NOT NULL,
created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE balance_adjustment (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
account_id bigint NOT NULL REFERENCES asset_account(id),
old_balance numeric(24,2) NOT NULL,
new_balance numeric(24,2) NOT NULL,
reason varchar(1000) NOT NULL,
created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE planned_occurrence ADD COLUMN payment_group_id bigint REFERENCES planned_occurrence(id);
CREATE INDEX ix_planned_occurrence_payment_group ON planned_occurrence(payment_group_id);

CREATE TABLE card_payment (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
card_id bigint NOT NULL REFERENCES payment_card(id),
account_id bigint NOT NULL REFERENCES asset_account(id),
payment_date date NOT NULL,
amount numeric(24,2) NOT NULL CHECK(amount>0),
occurrence_id bigint UNIQUE REFERENCES planned_occurrence(id),
created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE loan_repayment (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
loan_id bigint NOT NULL REFERENCES loan(id),
account_id bigint NOT NULL REFERENCES asset_account(id),
payment_date date NOT NULL,
principal numeric(24,2) NOT NULL CHECK(principal>=0),
interest numeric(24,2) NOT NULL CHECK(interest>=0),
fee numeric(24,2) NOT NULL CHECK(fee>=0),
early boolean NOT NULL,
entry_id bigint REFERENCES ledger_entry(id),
occurrence_id bigint UNIQUE REFERENCES planned_occurrence(id),
created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE loan_rate_history (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
loan_id bigint NOT NULL REFERENCES loan(id),
effective_date date NOT NULL,
old_rate numeric(12,8) NOT NULL,
new_rate numeric(12,8) NOT NULL CHECK(new_rate>=0),
created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE asset_snapshot (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
captured_at timestamptz NOT NULL DEFAULT now(),
total_assets numeric(24,2) NOT NULL,
total_debts numeric(24,2) NOT NULL,
net_assets numeric(24,2) NOT NULL,
sync_status varchar(2000) NOT NULL,
created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE snapshot_item (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
snapshot_id bigint NOT NULL REFERENCES asset_snapshot(id),
item_type varchar(10) NOT NULL CHECK(item_type IN ('ACCOUNT','LOAN','POSITION')),
entity_id bigint NOT NULL,
owner_code varchar(10) NOT NULL CHECK(owner_code IN ('HUSBAND','WIFE')),
asset_type varchar(20),
amount_krw numeric(24,2) NOT NULL,
details jsonb NOT NULL,
created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX ix_asset_account_withdrawal_account_id ON asset_account(withdrawal_account_id);
CREATE INDEX ix_payment_card_account_id ON payment_card(account_id);
CREATE INDEX ix_loan_account_id ON loan(account_id);
CREATE INDEX ix_category_parent_id ON category(parent_id);
CREATE INDEX ix_ledger_entry_category_id ON ledger_entry(category_id);
CREATE INDEX ix_ledger_entry_source_account_id ON ledger_entry(source_account_id);
CREATE INDEX ix_ledger_entry_target_account_id ON ledger_entry(target_account_id);
CREATE INDEX ix_ledger_entry_card_id ON ledger_entry(card_id);
CREATE INDEX ix_ledger_entry_replaces_id ON ledger_entry(replaces_id);
CREATE INDEX ix_initial_installment_card_id ON initial_installment(card_id);
CREATE INDEX ix_recurring_plan_category_id ON recurring_plan(category_id);
CREATE INDEX ix_recurring_plan_account_id ON recurring_plan(account_id);
CREATE INDEX ix_recurring_plan_target_account_id ON recurring_plan(target_account_id);
CREATE INDEX ix_recurring_plan_card_id ON recurring_plan(card_id);
CREATE INDEX ix_recurring_plan_loan_id ON recurring_plan(loan_id);
CREATE INDEX ix_planned_occurrence_plan_id ON planned_occurrence(plan_id);
CREATE INDEX ix_planned_occurrence_account_id ON planned_occurrence(account_id);
CREATE INDEX ix_planned_occurrence_target_account_id ON planned_occurrence(target_account_id);
CREATE INDEX ix_planned_occurrence_card_id ON planned_occurrence(card_id);
CREATE INDEX ix_planned_occurrence_loan_id ON planned_occurrence(loan_id);
CREATE INDEX ix_planned_occurrence_category_id ON planned_occurrence(category_id);
CREATE INDEX ix_planned_occurrence_entry_id ON planned_occurrence(entry_id);
CREATE INDEX ix_security_holding_account_id ON security_holding(account_id);
CREATE INDEX ix_security_trade_account_id ON security_trade(account_id);
CREATE INDEX ix_security_trade_entry_id ON security_trade(entry_id);
CREATE INDEX ix_ledger_entry_lookup ON ledger_entry(transaction_date,attribution,transaction_type);
CREATE INDEX ix_planned_occurrence_lookup ON planned_occurrence(due_date,state);
CREATE INDEX ix_snapshot_item_lookup ON snapshot_item(snapshot_id,owner_code,item_type);
CREATE INDEX ix_asset_snapshot_lookup ON asset_snapshot(captured_at);
CREATE INDEX ix_security_trade_lookup ON security_trade(account_id,trade_date);
CREATE INDEX ix_loan_rate_history_lookup ON loan_rate_history(loan_id,effective_date);
CREATE UNIQUE INDEX uq_category_name ON category(transaction_type,COALESCE(parent_id,0),name);
COMMENT ON TABLE asset_account IS '자산계좌: 소유권은 남편/부인, 공동 조회는 합산';
COMMENT ON COLUMN asset_account.id IS '고유 식별자';
COMMENT ON COLUMN asset_account.asset_type IS '자산 유형 CASH/SAVINGS/SECURITIES';
COMMENT ON COLUMN asset_account.owner_code IS '소유자 HUSBAND/WIFE; 공동 소유권 없음';
COMMENT ON COLUMN asset_account.institution_code IS '금융기관 Enum 코드';
COMMENT ON COLUMN asset_account.account_name IS '계좌명 또는 적금 상품명';
COMMENT ON COLUMN asset_account.account_number IS '전체 계좌번호';
COMMENT ON COLUMN asset_account.current_balance_krw IS '현재 원화 잔액 또는 증권 계좌 총평가액';
COMMENT ON COLUMN asset_account.currency_code IS '통화 코드';
COMMENT ON COLUMN asset_account.status IS '사용중 ACTIVE 또는 해지 CLOSED';
COMMENT ON COLUMN asset_account.kis_linked IS 'KIS API 현재 상태 연동 여부';
COMMENT ON COLUMN asset_account.start_date IS '가입일 또는 반복 시작일';
COMMENT ON COLUMN asset_account.maturity_date IS '만기일';
COMMENT ON COLUMN asset_account.interest_rate IS '연 금리 퍼센트';
COMMENT ON COLUMN asset_account.monthly_amount IS '월 납입액';
COMMENT ON COLUMN asset_account.payment_day IS '월 결제 또는 납입일 1~31; 없는 날짜는 말일';
COMMENT ON COLUMN asset_account.withdrawal_account_id IS '적금 출금 현금성 계좌 식별자';
COMMENT ON COLUMN asset_account.deposit_krw IS '증권 원화 예수금';
COMMENT ON COLUMN asset_account.deposit_usd IS '증권 달러 예수금';
COMMENT ON COLUMN asset_account.exchange_rate IS '원화 평가에 적용한 환율';
COMMENT ON COLUMN asset_account.last_synced_at IS '마지막 성공한 API 갱신 시각';
COMMENT ON COLUMN asset_account.created_at IS '최초 생성 시각';
COMMENT ON COLUMN asset_account.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE payment_card IS 'payment_card 업무 데이터 및 보존 이력';
COMMENT ON COLUMN payment_card.id IS '고유 식별자';
COMMENT ON COLUMN payment_card.card_name IS '카드명';
COMMENT ON COLUMN payment_card.owner_code IS '소유자 HUSBAND/WIFE; 공동 소유권 없음';
COMMENT ON COLUMN payment_card.card_type IS '체크 DEBIT 또는 신용 CREDIT';
COMMENT ON COLUMN payment_card.account_id IS '관련 계좌 식별자';
COMMENT ON COLUMN payment_card.payment_day IS '월 결제 또는 납입일 1~31; 없는 날짜는 말일';
COMMENT ON COLUMN payment_card.status IS '사용중 ACTIVE 또는 해지 CLOSED';
COMMENT ON COLUMN payment_card.created_at IS '최초 생성 시각';
COMMENT ON COLUMN payment_card.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE loan IS 'loan 업무 데이터 및 보존 이력';
COMMENT ON COLUMN loan.id IS '고유 식별자';
COMMENT ON COLUMN loan.loan_name IS '사용자 지정 대출명';
COMMENT ON COLUMN loan.owner_code IS '소유자 HUSBAND/WIFE; 공동 소유권 없음';
COMMENT ON COLUMN loan.initial_amount IS '최초 대출금액';
COMMENT ON COLUMN loan.current_balance IS '현재 대출잔액';
COMMENT ON COLUMN loan.interest_rate IS '연 금리 퍼센트';
COMMENT ON COLUMN loan.maturity_date IS '만기일';
COMMENT ON COLUMN loan.repayment_type IS '원금균등/원리금균등/만기일시상환 코드';
COMMENT ON COLUMN loan.payment_day IS '월 결제 또는 납입일 1~31; 없는 날짜는 말일';
COMMENT ON COLUMN loan.account_id IS '관련 계좌 식별자';
COMMENT ON COLUMN loan.status IS '사용중 ACTIVE 또는 해지 CLOSED';
COMMENT ON COLUMN loan.created_at IS '최초 생성 시각';
COMMENT ON COLUMN loan.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE category IS 'category 업무 데이터 및 보존 이력';
COMMENT ON COLUMN category.id IS '고유 식별자';
COMMENT ON COLUMN category.name IS '표시명';
COMMENT ON COLUMN category.transaction_type IS '거래 성격 INCOME/EXPENSE/TRANSFER';
COMMENT ON COLUMN category.parent_id IS '상위 대분류 식별자; NULL이면 대분류';
COMMENT ON COLUMN category.active IS '활성 상태; 비활성도 과거 이력 보존';
COMMENT ON COLUMN category.system_code IS '기본 카테고리 고정 식별코드';
COMMENT ON COLUMN category.created_at IS '최초 생성 시각';
COMMENT ON COLUMN category.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE ledger_entry IS '수입·지출·자산이동 원장. 취소 원본 보존';
COMMENT ON COLUMN ledger_entry.id IS '고유 식별자';
COMMENT ON COLUMN ledger_entry.transaction_date IS '실제 거래일';
COMMENT ON COLUMN ledger_entry.transaction_type IS '거래 성격 INCOME/EXPENSE/TRANSFER';
COMMENT ON COLUMN ledger_entry.amount IS '금액';
COMMENT ON COLUMN ledger_entry.attribution IS '거래 귀속 JOINT/HUSBAND/WIFE';
COMMENT ON COLUMN ledger_entry.category_id IS '선택 카테고리 식별자';
COMMENT ON COLUMN ledger_entry.payment_method IS '결제수단 ACCOUNT/DEBIT/CREDIT';
COMMENT ON COLUMN ledger_entry.source_account_id IS '거래 당시 출발 또는 카드 연결계좌';
COMMENT ON COLUMN ledger_entry.target_account_id IS '도착 또는 입금계좌';
COMMENT ON COLUMN ledger_entry.card_id IS '관련 카드 식별자';
COMMENT ON COLUMN ledger_entry.installment_months IS '할부개월; 1은 일시불';
COMMENT ON COLUMN ledger_entry.memo IS '선택 메모';
COMMENT ON COLUMN ledger_entry.origin IS '등록 출처 MANUAL/PLANNED/LOAN/KIS';
COMMENT ON COLUMN ledger_entry.voided IS '취소 여부; 원본은 삭제하지 않음';
COMMENT ON COLUMN ledger_entry.replaces_id IS '수정으로 대체한 원본 거래 식별자';
COMMENT ON COLUMN ledger_entry.created_at IS '최초 생성 시각';
COMMENT ON COLUMN ledger_entry.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE initial_installment IS 'initial_installment 업무 데이터 및 보존 이력';
COMMENT ON COLUMN initial_installment.id IS '고유 식별자';
COMMENT ON COLUMN initial_installment.card_id IS '관련 카드 식별자';
COMMENT ON COLUMN initial_installment.remaining_months IS '초기등록 시 잔여 할부개월';
COMMENT ON COLUMN initial_installment.remaining_amount IS '초기등록 시 잔여 할부총액; 신규 지출 아님';
COMMENT ON COLUMN initial_installment.memo IS '선택 메모';
COMMENT ON COLUMN initial_installment.active IS '활성 상태; 비활성도 과거 이력 보존';
COMMENT ON COLUMN initial_installment.created_at IS '최초 생성 시각';
COMMENT ON COLUMN initial_installment.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE recurring_plan IS 'recurring_plan 업무 데이터 및 보존 이력';
COMMENT ON COLUMN recurring_plan.id IS '고유 식별자';
COMMENT ON COLUMN recurring_plan.title IS '예정 표시 제목';
COMMENT ON COLUMN recurring_plan.plan_type IS '예정 성격 EXPENSE/CARD_PAYMENT/SAVINGS/LOAN';
COMMENT ON COLUMN recurring_plan.repeat_cycle IS '반복주기 ONCE/WEEKLY/MONTHLY/YEARLY';
COMMENT ON COLUMN recurring_plan.start_date IS '가입일 또는 반복 시작일';
COMMENT ON COLUMN recurring_plan.end_date IS '반복 종료일; NULL이면 종료일 없음';
COMMENT ON COLUMN recurring_plan.amount IS '금액';
COMMENT ON COLUMN recurring_plan.attribution IS '거래 귀속 JOINT/HUSBAND/WIFE';
COMMENT ON COLUMN recurring_plan.category_id IS '선택 카테고리 식별자';
COMMENT ON COLUMN recurring_plan.account_id IS '관련 계좌 식별자';
COMMENT ON COLUMN recurring_plan.target_account_id IS '도착 또는 입금계좌';
COMMENT ON COLUMN recurring_plan.card_id IS '관련 카드 식별자';
COMMENT ON COLUMN recurring_plan.loan_id IS '관련 대출 식별자';
COMMENT ON COLUMN recurring_plan.active IS '활성 상태; 비활성도 과거 이력 보존';
COMMENT ON COLUMN recurring_plan.created_at IS '최초 생성 시각';
COMMENT ON COLUMN recurring_plan.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE planned_occurrence IS '사용자 확인 전에는 집행하지 않는 예정거래';
COMMENT ON COLUMN planned_occurrence.id IS '고유 식별자';
COMMENT ON COLUMN planned_occurrence.source_key IS '자동생성 원천 유형과 식별자; 예정일과 UNIQUE';
COMMENT ON COLUMN planned_occurrence.due_date IS '원래 예정일; 반복 생성 중복방지 식별값';
COMMENT ON COLUMN planned_occurrence.title IS '예정 표시 제목';
COMMENT ON COLUMN planned_occurrence.plan_type IS '예정 성격 EXPENSE/CARD_PAYMENT/SAVINGS/LOAN';
COMMENT ON COLUMN planned_occurrence.plan_id IS '사용자 반복설정 식별자';
COMMENT ON COLUMN planned_occurrence.account_id IS '관련 계좌 식별자';
COMMENT ON COLUMN planned_occurrence.target_account_id IS '도착 또는 입금계좌';
COMMENT ON COLUMN planned_occurrence.card_id IS '관련 카드 식별자';
COMMENT ON COLUMN planned_occurrence.loan_id IS '관련 대출 식별자';
COMMENT ON COLUMN planned_occurrence.attribution IS '거래 귀속 JOINT/HUSBAND/WIFE';
COMMENT ON COLUMN planned_occurrence.amount IS '금액';
COMMENT ON COLUMN planned_occurrence.category_id IS '선택 카테고리 식별자';
COMMENT ON COLUMN planned_occurrence.state IS 'PENDING/COMPLETED/CANCELLED 처리상태';
COMMENT ON COLUMN planned_occurrence.actual_date IS '사용자가 변경한 예정일 또는 실제 확정일';
COMMENT ON COLUMN planned_occurrence.actual_amount IS '사용자가 확인한 실제 확정금액';
COMMENT ON COLUMN planned_occurrence.entry_id IS '연결 수입지출 원장 식별자';
COMMENT ON COLUMN planned_occurrence.created_at IS '최초 생성 시각';
COMMENT ON COLUMN planned_occurrence.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE security_holding IS 'security_holding 업무 데이터 및 보존 이력';
COMMENT ON COLUMN security_holding.id IS '고유 식별자';
COMMENT ON COLUMN security_holding.account_id IS '관련 계좌 식별자';
COMMENT ON COLUMN security_holding.symbol IS '증권 종목코드';
COMMENT ON COLUMN security_holding.name IS '표시명';
COMMENT ON COLUMN security_holding.currency_code IS '통화 코드';
COMMENT ON COLUMN security_holding.quantity IS '보유 또는 거래 수량';
COMMENT ON COLUMN security_holding.average_price IS '해당 통화 기준 평균매입단가';
COMMENT ON COLUMN security_holding.current_price IS '해당 통화 기준 현재가';
COMMENT ON COLUMN security_holding.value_native IS '해당 통화 기준 평가금액';
COMMENT ON COLUMN security_holding.value_krw IS '원화 환산 평가금액';
COMMENT ON COLUMN security_holding.exchange_rate IS '원화 평가에 적용한 환율';
COMMENT ON COLUMN security_holding.created_at IS '최초 생성 시각';
COMMENT ON COLUMN security_holding.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE security_trade IS 'security_trade 업무 데이터 및 보존 이력';
COMMENT ON COLUMN security_trade.id IS '고유 식별자';
COMMENT ON COLUMN security_trade.account_id IS '관련 계좌 식별자';
COMMENT ON COLUMN security_trade.external_id IS '외부 거래 고유 식별자; 계좌 내 중복방지';
COMMENT ON COLUMN security_trade.trade_date IS '증권 거래일';
COMMENT ON COLUMN security_trade.trade_type IS 'BUY/SELL/DEPOSIT/WITHDRAWAL/DIVIDEND';
COMMENT ON COLUMN security_trade.symbol IS '증권 종목코드';
COMMENT ON COLUMN security_trade.currency_code IS '통화 코드';
COMMENT ON COLUMN security_trade.quantity IS '보유 또는 거래 수량';
COMMENT ON COLUMN security_trade.amount IS '금액';
COMMENT ON COLUMN security_trade.exchange_rate IS '원화 평가에 적용한 환율';
COMMENT ON COLUMN security_trade.entry_id IS '연결 수입지출 원장 식별자';
COMMENT ON COLUMN security_trade.created_at IS '최초 생성 시각';
COMMENT ON COLUMN security_trade.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE entry_effect IS '거래 당시 계좌별 잔액 효과. 수정/취소 역분개 기준';
COMMENT ON COLUMN entry_effect.id IS '고유 식별자';
COMMENT ON COLUMN entry_effect.entry_id IS '연결 수입지출 원장 식별자';
COMMENT ON COLUMN entry_effect.account_id IS '관련 계좌 식별자';
COMMENT ON COLUMN entry_effect.delta IS '당시 계좌에 실제 반영한 부호 있는 금액; 취소 역분개 근거';
COMMENT ON COLUMN entry_effect.created_at IS '최초 생성 시각';
COMMENT ON COLUMN entry_effect.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE balance_adjustment IS 'balance_adjustment 업무 데이터 및 보존 이력';
COMMENT ON COLUMN balance_adjustment.id IS '고유 식별자';
COMMENT ON COLUMN balance_adjustment.account_id IS '관련 계좌 식별자';
COMMENT ON COLUMN balance_adjustment.old_balance IS '보정 전 현재 잔액';
COMMENT ON COLUMN balance_adjustment.new_balance IS '보정 후 현재 잔액';
COMMENT ON COLUMN balance_adjustment.reason IS '잔액 보정 사유';
COMMENT ON COLUMN balance_adjustment.created_at IS '최초 생성 시각';
COMMENT ON COLUMN balance_adjustment.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE card_payment IS 'card_payment 업무 데이터 및 보존 이력';
COMMENT ON COLUMN card_payment.id IS '고유 식별자';
COMMENT ON COLUMN card_payment.card_id IS '관련 카드 식별자';
COMMENT ON COLUMN card_payment.account_id IS '관련 계좌 식별자';
COMMENT ON COLUMN card_payment.payment_date IS '실제 출금 또는 상환일';
COMMENT ON COLUMN card_payment.amount IS '금액';
COMMENT ON COLUMN card_payment.occurrence_id IS '확정 원천 예정 식별자; 중복 집행 방지';
COMMENT ON COLUMN card_payment.created_at IS '최초 생성 시각';
COMMENT ON COLUMN card_payment.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE loan_repayment IS 'loan_repayment 업무 데이터 및 보존 이력';
COMMENT ON COLUMN loan_repayment.id IS '고유 식별자';
COMMENT ON COLUMN loan_repayment.loan_id IS '관련 대출 식별자';
COMMENT ON COLUMN loan_repayment.account_id IS '관련 계좌 식별자';
COMMENT ON COLUMN loan_repayment.payment_date IS '실제 출금 또는 상환일';
COMMENT ON COLUMN loan_repayment.principal IS '실제 상환 원금; 지출 아님';
COMMENT ON COLUMN loan_repayment.interest IS '실제 상환 이자; 지출 연결';
COMMENT ON COLUMN loan_repayment.fee IS '실제 중도상환수수료; 지출 연결';
COMMENT ON COLUMN loan_repayment.early IS '중도상환 여부';
COMMENT ON COLUMN loan_repayment.entry_id IS '연결 수입지출 원장 식별자';
COMMENT ON COLUMN loan_repayment.occurrence_id IS '확정 원천 예정 식별자; 중복 집행 방지';
COMMENT ON COLUMN loan_repayment.created_at IS '최초 생성 시각';
COMMENT ON COLUMN loan_repayment.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE loan_rate_history IS 'loan_rate_history 업무 데이터 및 보존 이력';
COMMENT ON COLUMN loan_rate_history.id IS '고유 식별자';
COMMENT ON COLUMN loan_rate_history.loan_id IS '관련 대출 식별자';
COMMENT ON COLUMN loan_rate_history.effective_date IS '변경 금리 적용일';
COMMENT ON COLUMN loan_rate_history.old_rate IS '적용 전 금리';
COMMENT ON COLUMN loan_rate_history.new_rate IS '변경 후 금리';
COMMENT ON COLUMN loan_rate_history.created_at IS '최초 생성 시각';
COMMENT ON COLUMN loan_rate_history.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE asset_snapshot IS 'asset_snapshot 업무 데이터 및 보존 이력';
COMMENT ON COLUMN asset_snapshot.id IS '고유 식별자';
COMMENT ON COLUMN asset_snapshot.captured_at IS '실제 스냅샷 저장 시각';
COMMENT ON COLUMN asset_snapshot.total_assets IS '스냅샷 총자산 KRW';
COMMENT ON COLUMN asset_snapshot.total_debts IS '스냅샷 총부채 KRW';
COMMENT ON COLUMN asset_snapshot.net_assets IS '스냅샷 순자산 KRW';
COMMENT ON COLUMN asset_snapshot.sync_status IS 'KIS 갱신 성공/실패/비활성 상태';
COMMENT ON COLUMN asset_snapshot.created_at IS '최초 생성 시각';
COMMENT ON COLUMN asset_snapshot.updated_at IS '마지막 수정 시각';
COMMENT ON TABLE snapshot_item IS '당시 소유자·이름·환율·수량을 포함한 스냅샷 상세';
COMMENT ON COLUMN snapshot_item.id IS '고유 식별자';
COMMENT ON COLUMN snapshot_item.snapshot_id IS '소속 스냅샷 식별자';
COMMENT ON COLUMN snapshot_item.item_type IS '스냅샷 항목 ACCOUNT/LOAN/POSITION';
COMMENT ON COLUMN snapshot_item.entity_id IS '원천 항목의 당시 식별자';
COMMENT ON COLUMN snapshot_item.owner_code IS '소유자 HUSBAND/WIFE; 공동 소유권 없음';
COMMENT ON COLUMN snapshot_item.asset_type IS '자산 유형 CASH/SAVINGS/SECURITIES';
COMMENT ON COLUMN snapshot_item.amount_krw IS '해당 항목의 당시 KRW 평가금액';
COMMENT ON COLUMN snapshot_item.details IS '당시 이름·소유자·수량·예수금·USD평가·환율을 포함한 JSON';
COMMENT ON COLUMN snapshot_item.created_at IS '최초 생성 시각';
COMMENT ON COLUMN snapshot_item.updated_at IS '마지막 수정 시각';
COMMENT ON COLUMN asset_account.display_order IS '유형별 사용자 지정 표시 순서';
COMMENT ON COLUMN payment_card.display_order IS '사용자 지정 카드 표시 순서';
CREATE INDEX idx_asset_account_display_order ON asset_account(asset_type, display_order, id);
CREATE INDEX idx_payment_card_display_order ON payment_card(display_order, id);
CREATE TABLE installment_schedule (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 installment_id bigint NOT NULL REFERENCES initial_installment(id) ON DELETE RESTRICT,
 due_date date NOT NULL,
 amount numeric(24,2) NOT NULL CHECK(amount>0),
 state varchar(12) NOT NULL CHECK(state IN ('PENDING','PAID','CANCELLED')),
 occurrence_id bigint REFERENCES planned_occurrence(id) ON DELETE RESTRICT,
 paid_date date,
 CHECK ((state='PAID' AND occurrence_id IS NOT NULL AND paid_date IS NOT NULL) OR
        (state<>'PAID' AND occurrence_id IS NULL AND paid_date IS NULL))
);
CREATE UNIQUE INDEX idx_installment_schedule_active_date
 ON installment_schedule(installment_id,due_date) WHERE state<>'CANCELLED';
CREATE TABLE kb_card_import (
 card_id bigint NOT NULL REFERENCES payment_card(id) ON DELETE RESTRICT,
 source_key varchar(64) NOT NULL,
 entry_id bigint NOT NULL REFERENCES ledger_entry(id) ON DELETE RESTRICT,
 created_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(card_id, source_key)
);
CREATE TABLE kb_card_mapping (
 source_card varchar(200) PRIMARY KEY,
 card_id bigint NOT NULL REFERENCES payment_card(id) ON DELETE RESTRICT,
 account_id bigint NOT NULL REFERENCES asset_account(id) ON DELETE RESTRICT,
 point_payment boolean NOT NULL DEFAULT false
);
CREATE TABLE kb_category_rule (
 merchant_key varchar(200) NOT NULL,
 industry_key varchar(200) NOT NULL,
 category_id bigint NOT NULL REFERENCES category(id) ON DELETE RESTRICT,
 PRIMARY KEY(merchant_key,industry_key)
);
CREATE TABLE IF NOT EXISTS kb_benefit_tier_choice (
 card_id bigint NOT NULL REFERENCES payment_card(id) ON DELETE RESTRICT,
 month char(7) NOT NULL CHECK(month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
 data jsonb NOT NULL, revision bigint NOT NULL DEFAULT 1, updated_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(card_id,month)
);
CREATE TABLE IF NOT EXISTS kb_benefit_plan (
 card_id bigint NOT NULL REFERENCES payment_card(id) ON DELETE RESTRICT,
 effective_month char(7) NOT NULL CHECK(effective_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
 data jsonb NOT NULL, revision bigint NOT NULL DEFAULT 1, updated_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(card_id,effective_month)
);
CREATE TABLE IF NOT EXISTS kb_benefit_usage (
 card_id bigint NOT NULL REFERENCES payment_card(id) ON DELETE RESTRICT,
 month char(7) NOT NULL CHECK(month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
 data jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(card_id,month)
);
CREATE TABLE kb_benefit_report (
 card_id bigint NOT NULL REFERENCES payment_card(id) ON DELETE RESTRICT,
 month char(7) NOT NULL CHECK(month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
 data jsonb NOT NULL,
 revision bigint NOT NULL DEFAULT 1,
 updated_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(card_id,month)
);
COMMIT;


